function declare_global()
    global TRAINING_DATA_START TRAINING_DATA_END NUM_OF_FEATURES NUM_OF_STOCKS_FOR_TRAINING ...
           NUM_OF_DAYS_TO_FORWARD_DAY NUM_OF_DAYS_IN_SAMPLE PORTION_OF_DATA POLY_ORDER

    TRAINING_DATA_START = 719;
    NUM_OF_DAYS_TO_FORWARD_DAY = 8;
    NUM_OF_DAYS_IN_SAMPLE = 30;

    TRAINING_DATA_END = NUM_OF_DAYS_TO_FORWARD_DAY + NUM_OF_DAYS_IN_SAMPLE;
    NUM_OF_FEATURES = TRAINING_DATA_START - TRAINING_DATA_END + 1;
    NUM_OF_STOCKS_FOR_TRAINING = 160;
    
    PORTION_OF_DATA = 10;
    POLY_ORDER = 4;
end

